#!/usr/bin/python3
first_number = int(input("Enter first No: "))
second_number = int(input("Enter Second No: "))
print()
print()
print("Doing the calculations....")
print("Converting to numbers....")
print()
print()
print("Sum of {} and {} is {}.".format(first_number, second_number, first_number + second_number))
print()
print("--Thank you for using our service--")
